### ISSUE TITLE
Fix BEM

### ISSUE THREAD

**Issue by ai** [imberette/gallery#2]
In BEM every file must contains only one block and affects only yo the blocks. But `grids.css`:

1. Has many blocks: `.grid`, `.lightbox`, `.grid-item`
2. Affect too tags outside of the block `* { box-sizing: border-box; }`
3. Also, you should know the good reason to disable Stylelint rules ;). Don’t do it just to remove a warning.
4. `body.css` contains `.page` block. But file name and block name should be equal.

**Comment by ai** [comment]
Right now I found `.person_links` in `links.css`

**Comment by ai** [comment]
`.header_info_list` — why do you have 3 `_`? ;) `_` only separates block and element. If you want 2 words block or element you use `-` to separate words in block and element.

**Comment by imberette** [comment]
Fixed  dee1b51958259ada27064c8f2ab7f156e1168516
